[tool.poetry]
name = "servus"
version = "0.1.0"
description = "A bavarian school project. Finally a messenger made by students for students."
authors = ["Servus Team"]
readme = "README.md"
requires-python = ">=3.12"
package-mode = false

[tool.poetry.dependencies]
flask = ">=3.0,<4.0"
flask-socketio = ">=5.3,<6.0"
psycopg2-binary = ">=2.9,<3.0"
bcrypt = ">=4.1,<5.0"
python-dotenv = ">=1.0,<2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"